
components:
- ../../../components/qmgr01
- ../../../components/ir01

secretGenerator:
- name: config-mqccdt-~flow~-secret
  behavior: create
  files:
  - ../../../base/mq2mq-ir/ccdt.json

# ENABLE SED REPLACE - this points to the SED transformer and enables it at this level in the YAML tree.
transformers:
- finalizer.yaml
# ENABLE SED REPLACE end