s/~tower~/Tower1/g
s/~function~/APP1QMGR/g
s/~log-format~/JSON/g
s/~QM~/APPQMGR2/g
s/~qm~/appqmgr2/g
s/~env~/DEV/g
s/~service~/App/g
s/~LICENSE~/L-QWBN-T3PKLE/g
s/~VERSION~/9.4.2.0-r2/g
s/~cpu-min~/200m/g
s/~cpu-max~/700m/g
s/~memory-min~/256Mi/g
s/~memory-max~/512Mi/g
s/~storage-size~/8Gi/g
s/~organisation~/IBM/g
