---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: active-cluster-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - nwg-z
    # - nwg
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - ocpz1
                - ocpz2
                # - nwg-mm
                # - nwg-mg