apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: prime-clusters-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - nwg-z
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - nwg-mg-z