apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - https://github.com/andrewdavies-net/gitops-components-library/components/ace/


generatorOptions:
 disableNameSuffixHash: true

patches:
- path: "ace.yaml"
  target:
    kind: "IntegrationRuntime"
    name: "IRFlow"