apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- https://github.com/ldesrosi/gitops-components-library/components/mq/native-ha/

generatorOptions:
 disableNameSuffixHash: true
 
# MERGE FILES INTO ONE - merge multiple files of the same name, across different sections of the YAML tree into one.
patchesStrategicMerge:
- ./qm.yaml
# MERGE FILES INTO ONE end

# --- CONFIGMAP CREATOR --- create configmaps from files you've added to insert into the QMGR build/creation.
# MQSC CONFIG - add 'static' MQSC files, whcih only take effect on inital build of the QMGR container/POD. This one merges other configs of the same name elsewhere in the YAML tree.
configMapGenerator:
#- name: mqsc-configmap
- name: ~qm~-mqsc-configmap
  behavior: merge
  files:
  - ./static-qm.mqsc
# --- CONFIGMAP CREATOR --- end

# CUSTOM QM.INI - add your own custom 'qm.ini' file
- name: ~qm~-mqsc-ini-config
  behavior: merge
  files:
   - ./qm.ini
# CUSTOM QM.INI end

- name: ~qm~-dynamic-mqsc-configmap
  behavior: create
  files:
  - dynamic-mqsc/dynamic-service.mqsc
  - dynamic-mqsc/dynamic-qmgr.mqsc
# --- CONFIGMAP CREATOR --- end
